name: hello-world-example

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test-hello-world.yml"

jobs:
  hello-world-example:
    name: "Test: Hello World"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello World
        run ${{ secrets.GITHUB_TOKEN }}
